apiVersion: apps/v1
kind: Deployment
metadata:
    name: fastapi
spec:
    replicas: 3
    selector:
        matchLabels:
            role: fastapi
    template:
        metadata:
            labels:
                role: fastapi
        spec:
            containers:
              - name: fastapi
                image: testmediumlabjs/github_actions_medium:41814dd338810d5f3960ee4e65e1b1163d4c995d
                resources:
                    limits:
                        cpu: 500m